### ISSUE TITLE
After AndroidX merge project is not syncing

### ISSUE THREAD

**Issue by Esselans** [Tunous/Dank#48]
Any ideas how to solve this? This is after AndroidX merge. I already installed all android studio recommended updates, clean and rebuilt, etc...

```
10:05	Gradle sync failed: 'Gradle: com.google.truth:truth:0.40@jar' already disposed: --------------Creation trace: 
			java.lang.Throwable: 1566047138269
			at com.intellij.openapi.util.TraceableDisposable.<init>(TraceableDisposable.java:44)
			at com.intellij.openapi.roots.impl.libraries.LibraryImpl.<init>(LibraryImpl.java:102)
			at com.intellij.openapi.roots.impl.libraries.LibraryImpl.<init>(LibraryImpl.java:74)
			at com.intellij.openapi.roots.impl.libraries.LibraryTableBase$LibraryModel.createLibrary(LibraryTableBase.java:298)
			at com.intellij.openapi.roots.impl.libraries.LibraryTableBase$LibraryModel.createLibrary(LibraryTableBase.java:291)
			at com.intellij.openapi.roots.impl.libraries.LibraryTableBase$LibraryModel.createLibrary(LibraryTableBase.java:285)
			at com.intellij.openapi.externalSystem.service.project.AbstractIdeModifiableModelsProvider.createLibrary(AbstractIdeModifiableModelsProvider.java:257)
			at com.android.tools.idea.gradle.project.sync.setup.module.android.AndroidModuleDe... (show balloon)
```

**Comment by Tunous** [comment]
Did you also try `File > Invalidate Caches / Restart`?

**Comment by Esselans** [comment]
> Did you also try `File > Invalidate Caches / Restart`?

Yeah. No luck. Will try checking out the repo again.

**Comment by Esselans** [comment]
Solved by deleting app/build folder manually
